### ISSUE TITLE
Intel MPI not working with pmix v2 and v3

### ISSUE THREAD

**Issue by lipixx** [pmix/pmix#1115] opened 2019-02-11 15:17 UTC
Coming from https://bugs.schedmd.com/show_bug.cgi?id=6418 we've found that Intel MPI is not
working with pmix v2 and pmix v3.

Intel MPI with pmix 1.2.5 works just fine.

```
]$ export I_MPI_PMI_LIBRARY=/home/lipi/bin/pmix/lib/libpmix.so
]$ /home/lipi/bin/intelmpi/compilers_and_libraries_2018.2.199/linux/mpi/intel64/bin/mpirun -n 2 /home/lipi/src/mpi_hello
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(805): fail failed
MPID_Init(1743)......: channel initialization failed
MPID_Init(2137)......: PMI_Init returned -1
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(805): fail failed
MPID_Init(1743)......: channel initialization failed
MPID_Init(2137)......: PMI_Init returned -1
```

Our question here is if you have any background information on why Intel MPI is not working starting at pmix v2 and what are the changes that broke this compatibility.

We guess that Intel MPI is who has to fix their code in order to adapt to new pmix libraries, but would like your point-of-view. This issue initially was raised at SchedMD as an Slurm bug but we definitively discarded a bug in our side since we reproduced the issue outside Slurm.

**Comment by rhc54** [comment] 2019-02-11 17:44
I read thru the Slurm bug report. Sadly, I don't know how to directly add those folks to this issue, so I'm going to copy this response over there (at least, the relevant parts).

1. Intel MPI doesn't directly link against any PMI(x) library to avoid licensing issues. This is why you don't see the linkage in the ```mpicc``` cmd line or when looking at the executable. Instead, IMPI looks for the ```I_MPI_PMI_LIBRARY``` envar that points it to the desired PMI(x) library to use and then internally ```dlopen's``` that library. It wasn't clear in the Slurm ticket if that envar was being set correctly in all cases One simple mistake is to not set the envar (which then defaults to looking for a PMI1 library) or to have it set to point to a Slurm PMI library while telling ```srun``` to use PMIx - that won't work and will generate the stated error.

1. In the example that does show that library correctly set, I'm seeing ```MPIR_xxx``` errors reported. This might be an error in OMPI itself - we know that the MPIR support in OMPI is broken in some series.

1. I'm not terribly surprised that using the PMIx libpmi2 causes odd behavior. The issue is that our PMI2 library simply shims the PMI2 calls into their PMIx equivalents. Thus, it expects Slurm to be using the PMIx lib, not their PMI2 one. Since it didn't find the expected server, every process just operated independently.

1. I'm not sure, but I do seem to recall that @artpol84 mentioned some changes to the Slurm plugin when moving from 1.2.5 to the 2.x series - perhaps he can comment on this one?

1. Obviously, you'll need to ask IMPI about PMIx v1 vs v2/3 support - I don't know what they targeted.

**Comment by rhc54** [comment] 2019-02-11 18:58
I'm unaware of any reason why that wouldn't work - let me ask my IMPI friends and get back here on it.

**Comment by rhc54** [comment] 2019-02-11 19:51
Just been told that IMPI 2018 doesn't directly support PMIx, so what is happening here is that you are actually falling back to the PMIx libpmi1 wrapper. It appears that IMPI is looking for some PMI envars as well as specific values being available from the server.

I'm therefore rather surprised that it worked with any PMIx version. I'll take a look, but I'm unaware of any change to the PMI backward-compatibility wrappers. I suspect instead that the updated Slurm plugin may no longer be providing a value IMPI was relying upon. Since that code is proprietary, you'd need to go thru the IMPI contract point to request they identify the missing value(s).

**Comment by rhc54** [comment] 2019-02-11 19:54
@artpol84 @karasevb Another approach would be to compare the PMI-1 plugin with the PMIx one and see what values might be missing. I suppose one could also compare the PMIx v1.2.5 plugin with that for PMIx v2.x and see if there is some obvious difference?

**Comment by justbennet** [comment] 2019-02-11 20:29
Thanks, Ralph.

The naming and versioning is a bit confusing, but it sounds like PMI2 and PMIx2 are both out with respect to IMPI and we should use the Slurm PMIx 1.2.5 plugin for IMPI jobs.

PMI2 is something from the MPICH side of the house, right, and that would be separate and distinct from PMIx, except insofar as PMIx is trying to provide a compatibility layer?

**Comment by rhc54** [comment] 2019-02-11 20:48
Sorry about the confusion - let me try to clarify. PMI-1 and PMI-2 are indeed both MPICH creations. The change in version there indicates a fairly major change to the API signatures themselves, and so the two are incompatible. I understand that IMPI defaults to support PMI-1 interfaces.

PMIx deliberately chose to maintain API-level compatibility across versions. We had a few hiccups at the start, but by v1.2.5 we had hit our stride. Accordingly, there are no API changes once you get beyond that point. Our version numbers instead reference the version of the Standard that the library supports. So PMIx v2.x supports the PMIx v2 Standard, PMIx v3.x supports the PMIx v3 Standard, etc.

We rev the PMIx Standard whenever a new API is added. We do, upon rare occasion, deprecate something and subsequently remove it - but we do our best to make that a rare event.

Just to make the transition easier, PMIx has always included a backward compatibility libraries for apps using PMI-1 and PMI-2. Basically, we expose the APIs for those definitions and convert the calls into the closest corresponding PMIx API. Unfortunately, due to time constraints, we don't cover every single PMI-1 or PMI-2 API - we cover all the ones typically used for MPI and maybe a few others.

While that still lets you compile and execute, it doesn't guarantee that things will still work. Every library has its own required set of information and we cannot guess them all - especially for proprietary libs. In this case, all we can do is look at the current Slurm plugins and try to match what they do. However, that takes some time and effort, and I don't know how closely the PMIx plugin matches the other options.

The fact that it worked for PMIx v1.2.5 is encouraging. My best guess is that the Slurm PMIx plugin made a change in going from PMIx v1.2.5 to PMIx v2 and v3 that eliminated/renamed some envar or key value that IMPI relied upon. @artpol84 has the best chance of spotting it - with luck, it won't be hard to restore support.

On the plus side, it sounds like you can continue with PMIx v1.2.5 for now...and I believe IMPI will be releasing PMIx support in the not-too-distant future, which should eliminate the problem going forward.

**Comment by lipixx** [comment] 2019-02-12 10:18
Ralph, thank you so much for your clarifications, they help a lot.

Just a note, Slurm is working well with all test cases, except for using Intel MPI with a PMIx > 1.2.5,
where it fails exactly as when I test to run completely outside Slurm, but as you noted and for
the future we will take into account that PMIx compatibility with PMI-1 and PMI-2 API may not be
always complete, and neither the perfect match with proprietary libs.

So right now, the problem in our SchedMD bug is clearly with IMPI support against PMIx, so really not
a PMIx or Slurm problem.

Thanks you again for your time and your enlightening explanations.

If Bennet doesn't have more questions I guess we can close this issue.

**Comment by justbennet** [comment] 2019-02-12 13:03
Ralph, yes, thank you for the detailed explanation. Please close this issue if you would like.

We purchase support from Intel, so I will see if they can shed any light.

**Comment by rhc54** [comment] 2019-02-12 13:56
Do please let us know here what happens - someone else may encounter the same problem ☹️  I'll go ahead and close it for now and we can reopen if it does result in something we need to address.

**Closed by rhc54** 2019-02-12 13:56 UTC
