### ISSUE TITLE
PMIx-2.1.0rc1/OpenMPI cross version interoperability

### ISSUE THREAD

**Issue by victorsndvg** [pmix/pmix#556] opened 2017-10-17 13:02 UTC
Hi all,

I tried to mix several combinations of OpenMPI versions linked against several PMIx versions.

It seems that using OpenMPI 3.0.0 and several  PMIx versions with the same major version (1.2.X or 2.X) works, but not if the PMIx major versions of the server and client are different.

I expect to have this kind of compatibility starting with PMIx-2.1.0. Now the RC1 is available, I checked again and seems not working.

I'm doing something wrong?
It's a PMix issue or an OpenMPI issue?
Can someone give me some lights about this?

Thanks in advance!

**Comment by rhc54** [comment] 2017-10-17 14:36
We can keep this issue here until we understand it better. Couple of questions:

* how are you testing this? If you build OMPI 3.0.0 dynamically (i.e., not configured with --enable-static --disable-shared), and then compile your app, the app will be dynamically linked to whichever PMIx was used for OMPI. However, if you then rebuild OMPI against a different PMIx and use that result to mpirun your app, then your app will automatically pickup the PMIx used for the new OMPI - and not the one you originally built it against.

This can be a problem when going from 1.2 to 2.x as two of the APIs changed signature. It was an unfortunate change, but necessary and "flagged" at the time. The only way to really test it is to build everything static so you maintain the intended PMIx code.

This raises the second question...

* what is the error you are seeing? Is the PMIx client unable to connect to the server?

**Comment by victorsndvg** [comment] 2017-10-18 06:48
Hi Ralph,

I'm doing this tests with Singularity containers. In one hand, I use `mpirun` from the host, where I have installed several OpenMPI versions linked against several PMIx versions. On the other hand I have a Singularity container with the same or another versions of OpenMPI and PMIx.

Till the moment mixed OpenMPI 2.0.0/1/2/3, 2.1.1 and 3.0.0 with PMIx 1.2.1/2/3, 2.0.0/1 and 2.1.0rc1. 

 In general, the results shown that OpenMPI 2.X cannot  be mixed with a different OpenMPI 2.X (inside/outside the container), but OpenMPI 3.0.0 can be mixed with OpenMPI 2.X. Regarding PMIx, we can mix different PATCH versions but not different MAJOR versions.

From some threads in this issue tracker or some other forums, I would expect to get this feature working from PMIx 2.1.0.

The error message received depends on the host and container configuration, I can report two different behaviours:
*  Host OpenMPI-3.0.0/PMIx-2.1.0rc1 - Container OpenMPI-2.X/PMIx-1.2.X
```
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
```
*  Host OpenMPI-3.0.0/PMIx-2.1.0rc1 - Container OpenMPI-3.0.0/PMIx-1.2.X
```
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  pmix init failed
  --> Returned value Server not available (-52) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_init failed
  --> Returned value Server not available (-52) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Server not available" (-52) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
```

This make sense? I'm doing something wrong?

Thanks in advance!

**Comment by rhc54** [comment] 2017-10-18 13:59
When mpirun starts your container, how does it set envars for the software operating inside that container? If you just run "env" instead of an MPI app inside the container (launched via mpirun), what does it see?

**Comment by victorsndvg** [comment] 2017-10-18 14:43
In general, all host environment variables can be seen inside the container.

Applying OMPI and PMIX strings to grep in the test you propose, I get the following output:

```
PMIX:    HOST 2.1.0rc1 - CONTAINER 2.1.0rc1
PMIX_NAMESPACE=2361196545
PMIX_ID=2361196545.0
CONTAINER_PMIX_SHORT_VERSION=210rc1
PMIX_RANK=0
CONTAINER_PMIX_VERSION=2.1.0rc1
PMIX_PTL_MODULE=tcp,usock
PMIX_SERVER_URI21=pmix-server.14162;tcp4://127.0.0.1:57763
HOST_PMIX_SHORT_VERSION=210rc1
HOST_PMIX_VERSION=2.1.0rc1
PMIX_GDS_MODULE=ds12,hash
PMIX_DSTORE_ESH_BASE_PATH=/scratch/92969/ompi.c7236.12529/pid.14162/pmix_dstor_14162
PMIX_SECURITY_MODE=native,none
PMIX_BFROP_BUFFER_TYPE=PMIX_BFROP_BUFFER_NON_DESC
PMIX_SERVER_TMPDIR=/scratch/92969/ompi.c7236.12529/pid.14162/0/0
PMIX_SERVER_URI2=pmix-server.14162;tcp4://127.0.0.1:57763
...
SLURM_CHECKPOINT_IMAGE_DIR=/mnt/lustre/scratch/home/cesga/vsande/SingularityImages/tests/OMPI_compatibility
OMPI_COMM_WORLD_RANK=0
OMPI_MCA_pmix=^s1,s2,cray,isolated
OMPI_MCA_orte_ess_num_procs=1
OMPI_MCA_ess_base_vpid=0
OMPI_MCA_ess_base_jobid=2361196545
OMPI_MCA_orte_launch=1
OMPI_MCA_orte_num_nodes=1
OMPI_COMM_WORLD_LOCAL_RANK=0
OMPI_MCA_orte_hnp_uri=2361196544.0;tcp://172.28.72.36,172.29.72.36,10.118.72.36,10.117.72.36:36170
OMPI_ARGV=/mnt/lustre/scratch/home/cesga/vsande/SingularityImages/tests/OMPI_compatibility/containers/pmix_210rc1/desired_hostlibs_custom_ompi_3.0.0_pmix_2.1.0rc1.img env
OMPI_MCA_initial_wdir=/mnt/lustre/scratch/home/cesga/vsande/SingularityImages/tests/OMPI_compatibility
HOST_OMPI_VERSION=3.0.0
OMPI_UNIVERSE_SIZE=1
OMPI_MCA_mpi_yield_when_idle=0
OMPI_COMMAND=run_singularity.sh
CONTAINER_OMPI_VERSION=3.0.0
OMPI_APP_CTX_NUM_PROCS=1
OMPI_FILE_LOCATION=/scratch/92969/ompi.c7236.12529/pid.14162/0/0
OMPI_MCA_orte_precondition_transports=ea9976267867fc2e-0da21201007f2729
OMPI_COMM_WORLD_LOCAL_SIZE=1
OMPI_MCA_orte_jobfam_session_dir=/scratch/92969/ompi.c7236.12529/pid.14162
OMPI_MCA_orte_tmpdir_base=/scratch/92969
PWD=/mnt/lustre/scratch/home/cesga/vsande/SingularityImages/tests/OMPI_compatibility
OMPI_MCA_orte_bound_at_launch=1
OMPI_COMM_WORLD_SIZE=1
CESGA_FAMILY_COMPILER=gcc
OMPI_FIRST_RANKS=0
SLURM_SUBMIT_DIR=/mnt/lustre/scratch/home/cesga/vsande/SingularityImages/tests/OMPI_compatibility
OMPI_MCA_orte_top_session_dir=/scratch/92969/ompi.c7236.12529
SINGULARITY_TARGET_PWD=/mnt/lustre/scratch/home/cesga/vsande/SingularityImages/tests/OMPI_compatibility
OMPI_MCA_orte_app_num=0
OMPI_MCA_orte_ess_node_rank=0
OMPI_MCA_ess=^singleton
OMPI_MCA_shmem_RUNTIME_QUERY_hint=mmap
LMOD_FAMILY_COMPILER=gcc
OMPI_COMM_WORLD_NODE_RANK=0
OMPI_NUM_APP_CTX=1
SINGULARITY_IMAGE=/mnt/lustre/scratch/home/cesga/vsande/SingularityImages/tests/OMPI_compatibility/containers/pmix_210rc1/desired_hostlibs_custom_ompi_3.0.0_pmix_2.1.0rc1.img
INCLUDE=/mnt/lustre/scratch/home/cesga/vsande/SingularityImages/tests/OMPI_compatibility/build/pmix_210rc1/openmpi-3.0.0/include:/mnt/lustre/scratch/home/cesga/vsande/SingularityImages/tests/OMPI_compatibility/build/pmix_2.1.0rc1/lib:/opt/cesga/singularity/2.3.2/include:/opt/cesga/easybuild/software/binutils/2.27-GCCcore-6.3.0/include:/opt/cesga/easybuild/software/GCCcore/6.3.0/include
OMPI_MCA_orte_local_daemon_uri=2361196544.0;tcp://172.28.72.36,172.29.72.36,10.118.72.36,10.117.72.36:36170
```

**Comment by rhc54** [comment] 2017-10-18 14:47
Hmmm. PMIx uses the TCP loopback device by default as clients are only supposed to connect back to their local PMIx server. Can a process in the container "see" the loopback device of a process outside the container?

There are PMIx flags to use a non-loopback device and/or to use the usock transport, but OMPI disables those and there currently isn't any way to override that setting. Might be something OMPI needs to address.

**Comment by rhc54** [comment] 2017-10-18 14:58
@jsquyres FWIW - we appear to add -lpthreads to LIBS, not CFLAGS. Are you saying that we also need to add it to LDFLAGS? It seems odd as I would have thought LIBS was the correct place.

**Comment by rhc54** [comment] 2017-10-18 15:00
sorry, I mean -pthreads of course

**Comment by victorsndvg** [comment] 2017-10-18 15:06
Sorry, I think the last 2 responses should be in other thread.

Regarding the loopback device, by default the container shares the same network namespaces as the host system and the same pid namespaces too. It should be straightforward I think

**Comment by ggouaillardet** [comment] 2017-10-18 15:07
It is ```-pthread``` (no 's') and you should be commenting on #555 

```config.log``` is attached, i will double check it tomorrow

**Comment by rhc54** [comment] 2017-10-18 16:42
Sorry for mixup. Problem here is that ompi disables usock in pmix 2.1 by default but pmix 1.2 only has usock

No ompi flag to override

**Comment by victorsndvg** [comment] 2017-10-19 08:27
Anything I can do to fix it in my installation?
Any suggestion?

**Comment by victorsndvg** [comment] 2017-10-19 15:17
Hi @rhc54 ,

sorry for the stupid question, but only for confirmation, I have to apply this patch to the PMIx-2.1.0rc1 sources that is going to be linked from the HOST OpenMPI-3.0.0. I don't need to do anything from the container side.

I'm right?

Thanks!

**Comment by rhc54** [comment] 2017-10-19 17:14
No, the patch is for OMPI v3.0.0 on the host side. As far as I can tell, there is nothing wrong with PMIx.

**Comment by victorsndvg** [comment] 2017-10-20 07:53
Ok @rhc54 , thanks for the responese.

I applied the patch and run with `mpirun -mca pmix_server_usock_connections 1`.

I got a new error:

```
[c7002:15542] Security mode none is not available
[c7002:15513] PACK-PMIX-VALUE: UNSUPPORTED TYPE 40
[c7002:15513] PMIX ERROR: ERROR in file gds_dstore.c at line 1628
[c7002:15513] PMIX ERROR: ERROR in file gds_dstore.c at line 1840
[c7002:15513] PMIX ERROR: ERROR in file gds_dstore.c at line 2201
[c7002:15513] PMIX ERROR: ERROR in file gds_dstore.c at line 2999
[c7002:15513] PMIX ERROR: ERROR in file gds_dstore.c at line 3031
[c7002:15513] PMIX ERROR: ERROR in file server/pmix_server.c at line 2134
[c7002:15542] PMIX ERROR: UNPACK-PAST-END in file src/client/pmix_client.c at line 186
slurmstepd: error: *** JOB 108520 ON c7002 CANCELLED AT 2017-10-20T09:39:59 DUE TO TIME LIMIT ***
```

Any idea?

**Comment by rhc54** [comment] 2017-10-20 14:04
Help me out a little - I gather you were running the mpirun from the patched OMPI v3.0.0, and you had what in the container?

**Comment by victorsndvg** [comment] 2017-10-20 14:54
Ok.

here in this tests, what I wanto to check is if host OpenMPI (server?) is able to handle different OpenMPI+PMIx inside the container.

I already checked that the same PMIx major version in&out the container works as expected.

Now, for this test, I'm using OpenMPI-3.0.0-patched and linked against PMIx-2.1.0rc1 at the host. 

I'm using several containers each one with a different combination of these libraries. This combinations include versions 2.0.0, 2.0.1, 2.0.3, 2.1.1, 3.0.0 of OpenMPI, linked agains PMIx 1.2.1 and 1.2.2.

Hope it helps!

**Comment by rhc54** [comment] 2017-10-20 14:57
So is the error you are reporting coming from the host side, or from a container? If so, which combination was in that container?

Note that you cannot mix those containers - all the containers in a given job _must_ contain the same version of OMPI and PMIx.

**Comment by victorsndvg** [comment] 2017-10-20 15:03
Each container was used in different batch jobs. I don't remember exactly, but I think all these executions returned the same error.

I don't know where the error come from... how can I now it?

I figure out the error is being reported from the client side (`ERROR: UNPACK-PAST-END in file src/client/pmix_client.c at line 186`), but something is not (well-)defined in the sever side (`PACK-PMIX-VALUE: UNSUPPORTED TYPE 40`)... I don't know too much things about OpenMPI internals ... 

I cannot answer your question.

**Comment by rhc54** [comment] 2017-10-20 15:07
Sure you can - look at the error output. It shows you the pid of the reporting process. I just need to know which of those pids was the container.

**Comment by victorsndvg** [comment] 2017-10-20 15:34
Singularity worflow assign the current PID of the host executable to the job running inside the container. PID is the same inside and outside the container.

What I can do is to try to run Singularity in debug mode to try to determine if the error occurs before starting the container job or during the execution of the contained binary.

**Comment by rhc54** [comment] 2017-10-20 15:56
Hmmm...no, that won't help. These errors are coming during execution. Let me try to debug a different way.

**Comment by victorsndvg** [comment] 2017-10-20 16:04
Let me know If I can do anything from my side!

**Comment by victorsndvg** [comment] 2017-10-27 08:54
Any new, fix or workaround about this?

**Comment by rhc54** [comment] 2017-10-27 18:01
I found and fixed a couple of bugs. The current state is that PMIx itself is now compatible from the v2.1 thru v1.2 branches, but only if you disable-dstore on the older versions and set PMIX_MCA_gds=hash on the v2.1 side. The shared memory (or dstore) support isn't working when crossing from v2.x to v1.x at this time. A couple of organizations are investigating the amount of work required to restore it.

Compatibility from v2.1 to v2.0 is verified even with dstore enabled. No known issues remain there.

On the OMPI side, things are a little more complicated. The OMPI community only promised to maintain cross-version support starting with OMPI v3.0, which is based on PMIx v2.0. So within the scope of that existing promise, everything should be fine. We are discussing with them a potential extension of the promise to cover the OMPI v2.x series - final resolution depends on the eventual resolution of the dstore issue.

Meantime, you could build the OMPI v2.x series against the current head of the PMIx v1.2 branch (I believe @jjhursey is going to release a release candidate tarball of it as well), configuring PMIx with --disable-dstore. You could then build the OMPI v3.x series with the head of the PMIx v2.1 branch, adding "gds=hash" to the default PMIx MCA parameter file. These combinations should work.

I'll keep this open until we resolve the dstore issue. Meantime, I hope this at least helps a bit.

**Comment by victorsndvg** [comment] 2017-10-30 11:32
@rhc54 , thanks for the elaborated response.

Before doing that, I need to do a newbie question regarding the following sentence:
> You could then build the OMPI v3.x series with the head of the PMIx v2.1 branch, adding "gds=hash" to the default PMIx MCA parameter file. These combinations should work.

How can I do that? Which file i need to modify (from the root of the OMPI git repository)?

ASAP I will report my results.

Thanks in advance.

**Comment by victorsndvg** [comment] 2017-11-02 14:53
Dear @rhc54 ,

I was able to try the workaround you explained, but it didn't work.
Container configuration is:
- PMIX 1.2.X (commit c9b633d) with flag `--disable-dstore`
- OpenMPI 2.0.1 

Host configuration is:
- PMIX 2.1.0 (commit a4fbe2f) adding `gds=hash` in the MCA parameter file
- OpenMPI 3.0.0

maybe I have to disable dstore also from OpenMPI side?

The error obtained is:
```--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)
--------------------------------------------------------------------------
```

I'm missing something?

Thanks in advance!

**Comment by rhc54** [comment] 2017-11-02 15:00
Which mca param file did you add "gds=hash" to? There should be one called "pmix-params.conf", and it needs to go in there.

**Comment by rhc54** [comment] 2017-11-02 15:02
If you want to just specify it in the environment, then add PMIX_MCA_gds=hash to the OMPI v3.0.0 environment.

**Comment by victorsndvg** [comment] 2017-11-02 15:03
I add the param to this file:
`$SOURCE_ROOT/etc/pmix-mca-params.conf`

**Comment by rhc54** [comment] 2017-11-02 15:04
Hmmm...that's the correct one. Not sure where the problem might lie.

**Comment by victorsndvg** [comment] 2017-11-02 15:05
Nothing special to do from the OpenMPI side?

**Comment by rhc54** [comment] 2017-11-02 15:07
Shouldn't be - I had no trouble running that combination, so I'll have to ponder awhile to see what might be the difference. Probably won't be for a bit as I'm up against deadlines.

**Comment by victorsndvg** [comment] 2017-11-02 16:13
O, don't worry. Let me know any news about this.

Thanks!

**Comment by rhc54** [comment] 2017-11-09 00:59
Okay, I dug into this and found the issues. It's purely a question of getting the two sides setup correctly. We'll need to do some work to make it more automatic, but for now you can make it work with a little effort. Here is the recipe I used - note that I don't have containers, so I built the OMPI v2.0 code with ```--enable-static --disable-shared``` to ensure there was no confusion over which PMIx library was being used.

On the OMPI v2.0.x side:

- configure PMIx v1.2.5 (the head of the v1.2 branch) with --disable-dstore

On the OMPI v3.0.x side:

- use the head of the OMPI v3.0.x branch - no special configure options

- no special configure options for PMIx v2.1.0 (use head of the v2.1 branch)

- add the following lines to the ```<prefix>/etc/pmix-mca-params.conf``` file (must be visible on all nodes)
```
ptl=usock
gds=hash
bfrops_base_default_type=x
```
where x = 1 if you configured OMPI v2.0.x without ```--enable-debug```, or x = 2 otherwise

I've tested this and it works for me - please let me know what you see.

Unfortunately, those parameters will need to change if you run a different OMPI version in the container. This is something we will fix as we move forward so the matching is done automatically.

**Comment by victorsndvg** [comment] 2017-11-09 08:27
Great! It also works for me :clap: :clap: 

Next week I will be in the BoF about containers-at-HPC at SC17. I will do a shot comment about this advance from PMIx side. In which version of PMIx you expect to have this feature working automatically? 2.1?

Finally, thanks for your great work and for your patience with me.

BR!

**Comment by rhc54** [comment] 2017-11-09 15:44
I'll talk to the other PMIx folks at today's telecon about it. We need one small change to v1.2.5, but that should be okay (I think) prior to releasing it. You'll still have to configure it with --disable-dstore as I don't think the dstore support will be fixed for awhile.

With that change, the v2.1.0 side should be able to handle things just fine. The only remaining issue is on the OMPI side of things. We didn't allow for someone to set a param directing PMIx to support the legacy usock connection method - by default, OMPI turns it off. We fixed that in OMPI v3.1, and I'll ask that it go back to v3.0. Once that is in place, you'll just need to set an OMPI param and everything should work.

I'll leave this open for now until we conclude those changes so we can update you. I was planning to attend the BoF (assuming the schedule fits) as I'd been working with Greg Kurtzer to help with MPI integration to Singularity during its initial days, so perhaps we'll meet there.

**Comment by victorsndvg** [comment] 2017-11-10 07:30
Ok, thank your for your explanations and your help.

Hope to see you there!

**Comment by victorsndvg** [comment] 2018-01-17 07:49
Hi @rhc54 !

I've seen that you have a new PMIx release candidate (https://github.com/pmix/pmix/releases/tag/v2.1.0rc2). Great job! It is supposed  to solve this issue, right?

In two weeks I will be able to check it, sorry but being very busy right now. There is something special I need to know for testing it?

**Comment by rhc54** [comment] 2018-01-17 08:44
Hi @victorsndvg !

Yes indeed - it should be the final fix. Only thing you need to know is that the corresponding release candidates for v1.2.5 and v2.0.3 are required for cross-version operation.

We may have to release before you are available to avoid blocking another project, but we can come back to make corrections if needed. We usually have a cleanup release in about 1 month when starting a new series, and then longer gaps thereafter.

**Comment by victorsndvg** [comment] 2018-02-21 07:51
Hi @rhc54 ,

sorry for the huge delay, but finally I was able to test pmix 2.1.0 (in the host) against pmix 1.2.5 and 2.0.3rc3 (in the container).

Maybe I'm missing something, but it's not working for me. Here I paste the errors for each configuration:

**OPENMPI: HOST 3.0.0 - CONTAINER 3.0.0**
**PMIX:    HOST 2.1.0 - CONTAINER 2.0.3**
```
gcc/6.3.0 loaded
singularity/2.4.2 loaded
===============================================================
OPENMPI: HOST 3.0.0 - CONTAINER 3.0.0
PMIX:    HOST 2.1.0 - CONTAINER 2.0.3
COMMAND: singularity exec /mnt/lustre/scratch/home/cesga/vsande/SingularityImages/tests/OMPI_compatibility/containers/pmix_203/desired_hostlibs_custom_ompi_3.0.0_pmix_2.0.3.img $
[c7235:19022] PMIX ERROR: ERROR in file dstore/pmix_esh.c at line 1723
[c7235:19022] PMIX ERROR: OUT-OF-RESOURCE in file dstore/pmix_esh.c at line 831
[c7235:19022] PMIX ERROR: OUT-OF-RESOURCE in file dstore/pmix_esh.c at line 1030
[c7236:23793] PMIX ERROR: ERROR in file dstore/pmix_esh.c at line 1723
[c7236:23793] PMIX ERROR: OUT-OF-RESOURCE in file dstore/pmix_esh.c at line 831
[c7236:23793] PMIX ERROR: OUT-OF-RESOURCE in file dstore/pmix_esh.c at line 1030
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[c7235:19022] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were $
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[c7236:23793] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were $
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[35090,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```

**OPENMPI: HOST 3.0.0 - CONTAINER 2.0.0**
**PMIX:    HOST 2.1.0 - CONTAINER 1.2.5**
```
gcc/6.3.0 loaded
singularity/2.4.2 loaded
===============================================================
OPENMPI: HOST 3.0.0 - CONTAINER 2.0.0
PMIX:    HOST 2.1.0 - CONTAINER 1.2.5
COMMAND: singularity exec /mnt/lustre/scratch/home/cesga/vsande/SingularityImages/tests/OMPI_compatibility/containers/pmix_125/desired_hostlibs_custom_ompi_2.0.0_pmix_1.2.5.img $
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[c7235:18767] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were $
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[c7236:23554] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were $
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[35437,1],1]
```

Maybe I'm missing something?

**Comment by rhc54** [comment] 2018-02-21 08:00
I'm afraid the OMPI folks decided that they will not support compatibility across major releases, so your second test case (```OPENMPI: HOST 3.0.0 - CONTAINER 2.0.0```) will not work.

I'll have to look at the first one - that should work out-of-the-box.

**Comment by victorsndvg** [comment] 2018-02-21 08:40
Ok, thanks!

**UPDATE:**

With this combination:

**OPENMPI: HOST 3.0.0 - CONTAINER 3.0.0**
**PMIX:    HOST 2.1.0 - CONTAINER 1.2.5**

I get the same error than using OpenMPI 2.0.0 inside the container.

**Comment by rhc54** [comment] 2018-02-21 16:41
OMPI 3.0.0 and above defaults to only using the tcp channel of PMIx, which means the usock channel used in PMIx v1.2.5 isn't supported. However, you can get OMPI to "enable" the usock channel by adding the pmix_server_usock_connections=1 MCA parameter to the host side.

Note that having OMPI 2.x in the container _may_ work - they just don't guarantee it. You'll still need to set that MCA param.

**Comment by victorsndvg** [comment] 2018-02-22 08:57
Hi @rhc54 ,

I change the call to mpirun with this flag:
```
mpirun -mca pmix_server_usock_connections 1 singularity  ...
```
And  nothing changes.

Sorry for the ignorance ... but this is the right place to do it? or I should modify `<prefix>/etc/pmix-mca-params.conf`? How can I do it?

Thanks for your help!

**Comment by rhc54** [comment] 2018-02-22 21:35
Hmmm...I just checked PMIx v2.1.1 against v2.0.3 and v1.2.5, and everything worked fine. This makes me suspect something is going on in OMPI, and not PMIx. I'll try one of your configurations and see if I can reproduce it

**Comment by ggouaillardet** [comment] 2018-02-23 02:04
FWIW

By using the `orte_fork_agent`, I forced on a single node
 - `mpirun` is the latest `v3.0.x` branch using `pmix-2.1.1rc1`
 - `hello_c` is linked with the latest `v3.0.x` branch using `pmix-1.2.5`

Honestly, I am not even sure this is a supported use case.
But if it is, then `PMIx_Init()` fails in `hello_c` because the `PMIX_SERVER_URI` environment variable is not set.

**Comment by rhc54** [comment] 2018-02-23 02:09
Could you explain in more detail what you did? I'm not finding any issues, but if you are going to run against pmix-1.2.5, then you have to tell mpirun to allow use of the usock transport - it does not enable it by default.

**Comment by ggouaillardet** [comment] 2018-02-23 02:24
my bad, once I
`mpirun -mca pmix_server_usock_connections 1 ...`
then it just works !

**Comment by rhc54** [comment] 2018-02-23 02:51
Great! Thx

**Comment by rhc54** [comment] 2018-02-23 02:54
@victorsndvg I suspect that the OMPI v3.0.0 code is missing some glue. Could you try your tests again with OMPI v3.0.1rc2? We are getting ready to release it, and it should match what @ggouaillardet did.

If that still doesn't work, then I'm beginning to suspect there is something going on involving Singularity.

**Comment by ggouaillardet** [comment] 2018-02-23 05:02
@victorsndvg the `pmix_server_usock_connections` MCA is not in Open MPI 3.0.0, so I suggest you try to build from git or the 3.0.1rc2 tarball

@rhc54 it seems I previously missed some error message

```
$ mpirun -np 1 --mca orte_fork_agent $HOME/fork_agent.v3.0.x-pmix-1.2.5 --mca pmix_server_usock_connections 1 ./hello_c
[motomachi.aics.kobe.rist.or.jp:31776] PMIX ERROR: UNKNOWN-DATA-TYPE in file ../../../../../../src/pmix-2.1.0/src/mca/gds/ds12/gds_dstore.c at line 3037
[motomachi.aics.kobe.rist.or.jp:31776] PMIX ERROR: UNKNOWN-DATA-TYPE in file ../../../src/pmix-2.1.0/src/server/pmix_server.c at line 1666
Hello, world, I am 0 of 1, (Open MPI v3.0.1rc3, package: Open MPI gilles@motomachi.aics.kobe.rist.or.jp Distribution, ident: 3.0.1rc3, repo rev: v3.0.1rc2-27-g159d76b, Unreleased developer copy, 166)
```

note the error messages do not prevent the app from running successfully.

**Comment by rhc54** [comment] 2018-02-23 14:52
I see a ```pmix-2.1.0``` in the path of that error message. I take it you are built against an external 2.1.0 copy of PMIx? There were a few bugs in that version, so we upgraded OMPI to v2.1.1. Might be worth trying with that one.

**Comment by ggouaillardet** [comment] 2018-02-26 02:09
@rhc54 I confirm the error message is no more there is I use `pmix-2.1.1rc1` instead of `pmix-2.1.0`, so as far as I am concerned, everything is fine now.

Bottom line
 - do __not__ use `Open MPI 3.0.0`, it misses support for the `pmix_server_usock_connections` MCA param
 - do __not__ use `PMIx 2.1.0`, it has a bug (not a fatal one though)

**Comment by rhc54** [comment] 2018-02-26 02:11
Excellent! Thanks for taking the time to chase it down. I will post something on the web site about it to try and help people.

**Comment by rhc54** [comment] 2018-03-28 03:54
I'm going to close this for now as the web site now contains info on PMIx compatibility, and the OMPI folks are going to add something over there about how it correlates to OMPI

**Closed by rhc54** 2018-03-28 03:54 UTC
